config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'

  get 'comments/destroy'

  resources :comments, only: [:edit, :destroy]

  devise_for :companies
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  get 'search_suggestions' => 'doctors#search_suggestions', as: :search_suggestions

  resources :doctors, only: [:show, :index, :create, :update, :edit, :destroy] do
    get 'send_password', to: 'doctors#send_password', on: :collection
    resources :comments, only: [:create]
  end

  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/services'
  get 'welcome/works'

  get 'companies/index', to: 'companies#index'
  resources :companies, only: [:show, :index, :create, :update, :edit, :destroy] do
    resources :comments, only: [:create]
  end
  get 'company/doctors', to: 'companies#doctors'
  get 'company/schedule', to: 'companies#schedule'

  root 'welcome#index'

  get 'doc', to: 'doctors#login'
  match 'doc/login', to: 'doctors#create_session', via: [:put, :patch, :get]
  match 'doc/logout', to: 'doctors#logout', via: [:put, :patch, :get]

  resources :schedules, only: [:show, :new,  :create, :update, :edit, :destroy]
  resources :records, only: [:create, :destroy]

end

app/models/company.rb
class Company < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :image, CompanyUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :doctors
  has_many :schedules
  has_many :comments

  validates_presence_of :name, :phone, :address, :description, :image, :activity
  validates :name, length: {in: 2..40}
  validates :description, length: {in: 100..500}
  validates :phone, numericality: true
  validates :name, :phone, uniqueness: true
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = params[:activity].present? ? Company.where('lower(activity) LIKE ?', "%#{params[:activity]}%") : Company.all
  end

  def show
    @company = Company.find(params[:id])
    @commented_object = @company
    @comments = @company.comments
  end

  def doctors
  end

  def schedule
    @company = current_company
    @doctors = @company.doctors
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/doctors.html.erb
<div class="container">
  <div class="row">
    <div class="box">
      <div class="col-lg-12">
        <h1>Список лікарів</h1>
        <h2 class="intro-text text-right">
          <button id="add-new" type="button" class="btn btn-success">Додати нового</button>
        </h2>
      </div>
      <div class="col-lg-12 add-new-doctor">
        <%= form_for Doctor.new do |f| %>
            <form>
              <div class="top-margin col-md-3">
                <label>Імя <span class="text-danger">*</span></label>
                <%= f.text_field :name, class: 'form-control', autofocus: true, required: true, placeholder: "Іван" %>
              </div>
              <div class="top-margin col-md-3">
                <label>Фамилия <span class="text-danger">*</span></label>
                <%= f.text_field :second_name, class: 'form-control', required: true, placeholder: "Іванов" %>
              </div>
              <div class="top-margin col-md-3">
                <label>отчес <span class="text-danger">*</span></label>
                <%= f.text_field :surname, class: 'form-control', required: true, placeholder: "Іванович" %>
              </div>
              <div class="top-margin col-md-3">
                <label>категория<span class="text-danger">*</span></label>
                <%= f.text_field :category, class: 'form-control', required: true, placeholder: "вищої" %>
              </div>
              <br>
              <div class="top-margin col-md-3">
                <label>специализация<span class="text-danger">*</span></label>
                <%= f.text_field :specialization, class: 'form-control', required: true, placeholder: "хірург" %>
              </div>
              <div class="top-margin col-md-3">
                <label>фото<span class="text-danger">*</span></label>
                <%= f.file_field :photo, class: 'form-control', required: true, placeholder: "фото" %>
              </div>
              <div class="top-margin col-md-3">
                <label>email<span class="text-danger">*</span></label>
                <%= f.email_field :email, class: 'form-control', required: true, placeholder: "Email" %>
              </div>
              <div class="top-margin col-md-3">
                <label>pass<span class="text-danger">*</span></label>
                <%= f.text_field :password, class: 'form-control', required: true, placeholder: "password" %>
              </div>
              &nbsp;
              <div class="thin text-center">
                <%= f.submit "Додати", class: 'btn btn-success' %>
              </div>

            </form>
        <% end %>

        <div class="doctor-info">
          <p id="name"></p>
          <p id="second_name"></p>
          <p id="surname"></p>
          <p id="email"></p>
          <p id="password"></p>
        </div>
      </div>

      <% current_company.doctors.each do |doctor| %>
          <div class="col-sm-12  doctor-list-item">
            <div class="container-fluid well span6">
              <div class="row-fluid">
                <div class="col-md-2">
                  <%= image_tag(doctor.photo.url(:medium), class: 'img-circle') %>
                </div>

                <div class="col-md-3">
                  <h3><%= doctor.surname %></h3>
                  <h3><%= doctor.name %></h3>
                  <h3><%= doctor.second_name %></h3>
                </div>
                <div class="col-md-5">
                  <h4>Лікар <%= doctor.category %> категорії </h4>
                  <h4>Спеціалізація  <%= doctor.specialization %> </h4>
                  <h4>Email: <%= doctor.email %></h4>

                </div>
                <div class="col-md-2">
                  <%= link_to 'Редагувати лікаря', edit_doctor_path(doctor), class: 'btn btn-info btn-block' %>
                  <%= link_to 'Видалити лікаря', doctor, class: "btn  btn-danger btn-block", method: :delete, data: {confirm: 'Are you sure?'} %>
                  <% unless doctor.schedule.present? %>
                    <%= link_to 'Створити розклад', new_schedule_path(doctor_id: doctor), class: 'btn btn-info btn-block', data: { no_turbolink: true } %>
                  <% else %>
                    <%= link_to 'Редагувати графік', edit_schedule_path(doctor.schedule), class: 'btn btn-info btn-block', data: { no_turbolink: true } %>
                  <% end %>

                </div>
              </div>
            </div>
          </div>
      <% end %>

    </div>
  </div>
</div>

<script>
  $(document).ready(function () {
    $('#add-new').click(function () {
      $('.add-new-doctor').show()
      $('#doctor_name').focus()
    })
  });
  $('doctor-info').hide();
  $('#doctor_password').click(function () {
    var randomstring = Math.random().toString(36).slice(-8);
    $(this).val(randomstring);
  });

  $('#new_doctor').submit(function (evt) {
    email = $('#doctor_email').val();
    password = $('#doctor_password').val();
    $.get( "/doctors/send_password", { email: email, password: password }, 'application/json');
  });
</script>

app/views/companies/index.html.erb
<div id="blue">
  <div class="container">
    <div class="row centered">
      <div class="col-lg-8 col-lg-offset-2">
        Список клінік
      </div>
    </div><!-- row -->
  </div><!-- container -->
</div><!--  bluewrap -->
<% @companies.each do |company| %>


    <div class="container">

      <div class="row">
        <div class="box">
          <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center"><strong><%= link_to company.name, company_path(company) %></strong>
            </h2>
            <hr>
          </div>
          <div class="col-md-6">
            <%= link_to company_path(company) do %>
                <%= image_tag company.image, class: 'img-responsive img-border-left' if company.image? %>
            <% end %>
          </div>
          <div class="col-md-6">
            <p><%= company.email %></p>
            <p><%= company.address %></p>
            <p> <%= company.phone %></p>
            <% if company.activity.present? %>
                <% company.activity.split(%r{,+\s+|,+|\s+}).each do |activity| %>
                    <div class="btn btn-success btn-xs"><%= link_to activity, companies_index_path(activity: activity) %></div>
                <% end %>
            <% end %>
          </div>

          <div class="col-md-12">
            <%= company.description %>
          </div>
          <div class="clearfix"></div>
        </div>
      </div>
    </div>


<% end %>

app/views/companies/schedule.html.erb
<div id="blue">
  <div class="container">
    <div class="row centered">
      <div class="col-lg-8 col-lg-offset-2">
        <h4>График компании </h4>

      </div>
    </div><!-- row -->
    <p align="center" class="btn-danger" > Следующая генерация графика будет <%=  Date.today.at_beginning_of_week+6.day %>  в 23:59</p>
  </div><!-- container -->
</div><!--  bluewrap -->
<div class="container">
  <table class="table table-condensed">
    <thead>

    </thead>
    <tbody>
    <% @doctors.each do |doctor, index| %>
        <tr>
          <% index = Date.today.at_beginning_of_week %>
          <th>Ім'я лікаря</th>
          <% today = Date.today %>
          <% (today.at_beginning_of_week..today.at_end_of_week).map.each do |day| %>
              <th><%= day.strftime("%A - %D") %></th>
          <% end %>
        </tr>
        <tr>
          <td><%= doctor.name %></td>
          <% Date::DAYNAMES.rotate(1).each do |weekday| %>
              <td>
                <% index = index + 1.day %>
                <div class="btn-success"> <%= p index-1.day %> </div>
                <br>
                <% if is_weekend?(doctor.current_schedule, weekday) %>
                    <p align="center" class="btn-danger"><br>Вихідний</p>
                <% else %>
                    <p align="center" class="btn-warning">Час роботи<br>
                      <%= doctor.current_schedule.send(weekday.downcase+'_start_time').strftime("%H - %M :") %>
                      <%= doctor.current_schedule.send(weekday.downcase+'_finish_time').strftime("%H - %M") %>
                    </p>
                    <br>
                    <% (doctor.current_schedule.send(weekday.downcase+'_start_time').to_i..doctor.current_schedule.send(weekday.downcase+'_finish_time').to_i).step(doctor.current_schedule.interval.minutes).to_a[0...-1].each do |interval| %>
                        <% iteration_day = index-1.day %>
                        <% iteration_time = Time.at(interval).utc %>
                        <% record_time = Time.new(iteration_day.year, iteration_day.month, iteration_day.day, iteration_time.hour, iteration_time.min, '00:00') %>
                        <% if Record.where(time: record_time, doctor_id: doctor.id).present? %>
                            <span class="dropdown">
                              <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">  <%= iteration_time.strftime("%H - %M") %>
                                <span class="caret"></span></button>
                              <ul class="dropdown-menu">
                                <li>
                                  <a href="#"><%= Record.where(time: record_time, doctor_id: doctor.id).first.user.name %></a>
                                </li>
                                <li>
                                  <a href="#"> <%= Record.where(time: record_time, doctor_id: doctor.id).first.user.surname %></a>
                                </li>
                                <li>
                                  <a href="#"> <%= Record.where(time: record_time, doctor_id: doctor.id).first.user.phone %></a>
                                </li>
                              </ul>
                            </span>
                        <% else %>
                            <%= iteration_time.strftime("%H - %M") %>
                        <% end %>
                        <br>
                    <% end %>
                <% end %>
              </td>
          <% end %>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/companies/show.html.erb
<div class="container">

  <div class="row">
    <div class="box">
      <div class="col-lg-12">
        <hr>
        <h2 class="intro-text text-center"><strong><%= @company.name %></strong>
        </h2>
        <hr>
      </div>
      <div class="col-md-6">
        <%= image_tag @company.image, class: 'img-responsive img-border-left' if @company.image? %>
      </div>
      <div class="col-md-6">
        <p><%= @company.email %></p>
        <p><%= @company.address %></p>
        <p> <%= @company.phone %></p>
      </div>

      <div class="col-lg-12">
        <%= @company.description %>
      </div>
      <div class="clearfix"></div>
      <iframe  width=100% height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"
               src = "https://maps.google.com/maps?q=<%= @company.lat %>,<%= @company.lng %>&hl=es;z=14&amp;output=embed"></iframe>
    </div>
  </div>



  <% @company.doctors.each do |doctor| %>
      <div class="col-sm-12  doctor-list-item">
        <div class="container-fluid well span6">
          <div class="row-fluid">
            <div class="col-md-2">
              <%= image_tag(doctor.photo.url(:medium), class: 'img-circle') %>
            </div>

            <div class="col-md-3">
              <h3><%= doctor.surname %></h3>
              <h3><%= doctor.name %></h3>
              <h3><%= doctor.second_name %></h3>
            </div>
            <div class="col-md-5">
              <h4>Лікар <%= doctor.category %> категорії </h4>
              <h4>Спеціалізація  <%= doctor.specialization %> </h4>
              <h4>Email: <%= doctor.email %></h4>

            </div>
            <div class="col-md-2">
              <%= link_to 'Записатися до лікаря', doctor_path(doctor), class: 'btn btn-info btn-block' %>


            </div>
          </div>
        </div>
      </div>
  <% end %>
  
  <h3>Відгуки</h3>
  <div id="comments-container">
    <%= render @comments %>
  </div>
  <div id="add_comment">
  <% if current_user %>
    <%= render 'comments/form' %>
  <% end %>
  </div>

</div>