config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'

  get 'comments/destroy'

  resources :comments, only: [:edit, :destroy]

  devise_for :companies
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  get 'search_suggestions' => 'doctors#search_suggestions', as: :search_suggestions

  resources :doctors, only: [:show, :index, :create, :update, :edit, :destroy] do
    get 'send_password', to: 'doctors#send_password', on: :collection
    resources :comments, only: [:create]
  end

  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/services'
  get 'welcome/works'

  get 'companies/index', to: 'companies#index'
  resources :companies, only: [:show, :index, :create, :update, :edit, :destroy] do
    resources :comments, only: [:create]
  end
  get 'company/doctors', to: 'companies#doctors'
  get 'company/schedule', to: 'companies#schedule'

  root 'welcome#index'

  get 'doc', to: 'doctors#login'
  match 'doc/login', to: 'doctors#create_session', via: [:put, :patch, :get]
  match 'doc/logout', to: 'doctors#logout', via: [:put, :patch, :get]

  resources :schedules, only: [:show, :new,  :create, :update, :edit, :destroy]
  resources :records, only: [:create, :destroy]

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  has_secure_password
  mount_uploader :photo, DoctorUploader

  belongs_to :company
  has_one :schedule
  has_one :current_schedule
  has_many :records
  has_many :comments

  validates_presence_of :name, :surname, :second_name, :specialization, :photo, :email
  validates :name, :surname, :second_name, length: {in: 2..20}
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def index
    @doctors = Doctor.all
  end

  def show
    @doctor = Doctor.find(params[:id])
    @commented_object = @doctor
    @comments = @doctor.comments
  end

  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      respond_to do |format|
        format.json { render json: @doctor }
        format.html { redirect_to :back }
      end
    end
  end

  def update
    @doctor = Doctor.find(params[:id])

    if @doctor.update(doctor_params)
      redirect_to edit_company_registration_path
    else
      format.html { render action: "edit" }
    end
  end

  def edit
    if current_company
      @doctor = Doctor.find(params[:id])
      redirect_to root_path unless current_company.id == @doctor.company.id
    else
      redirect_to root_path
    end
  end

  def login
    if current_doctor
      redirect_to current_doctor
    elsif current_company || current_user
      redirect_to root_path
    end
  end

  def create_session
    @doctor = Doctor.find_by(email: params[:email])
    if @doctor
      if @doctor.authenticate(params[:password])
        session[:doctor_id] = @doctor.id
        flash[:notice]='You successful login'
        redirect_to @doctor
      else
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end

  def logout
    reset_session
    redirect_to root_path
  end

  def destroy
    @doctor = Doctor.find(params[:id])
    if current_company && current_company.id == @doctor.company.id
      @doctor.destroy
      respond_to do |format|
        format.html { redirect_to company_doctors_path, notice: 'Doctor was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      format.html { redirect_to company_doctors_path, notice: 'unprocessable_entity' }
    end
  end

  def send_password
    password = params[:password]
    email = params[:email]
    DoctorMailer.new_doctor_notification(email, password).deliver_now
    DoctorMailer.company_notification(email, password, current_company.email).deliver_now

    redirect_to root_path
  end

  def search_suggestions
    query = params[:query]
    results = if params[:query].present?
                response = []
                Doctor.where('name ILIKE ? OR surname ILIKE ?', "%#{query}%", "%#{query}%").each do |doctor|
                  obj = {id: doctor.id, fullname: doctor.name + ' ' + doctor.surname, photo: doctor.photo.url(:small)}
                  response << obj
                end
                response
              else
                []
              end
    render json: results
  end

  private

  def doctor_params
    params.require(:doctor).permit(:name, :second_name, :surname, :password, :email, :category, :specialization, :photo).merge(company_id: current_company.id)
  end
end

app/helpers/concerns/doctors_helper.rb
module Concerns::DoctorsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/create.html.erb
<h1>Doctors#create</h1>
<p>Find me in app/views/doctors/create.html.erb</p>

app/views/doctors/edit.html.erb
<div id="blue">
  <div class="container">
    <div class="row centered">
    </div><!-- row -->
  </div><!-- container -->
</div><!-- blue wrap -->
<%= form_for(@doctor) do |f| %>
    <div class="container">
      <div class="row">
        <div class="col-lg-6 centered">
          <div class="tilt">
            <a href="#"><%= image_tag("p01.png") %></a>
          </div>
        </div><!-- col-lg-6 -->
        <div class="col-lg-6">
          <h4>Лікар</h4>
          <h4>
            <div class="field">
              Прізвище<br>
              <%= f.text_field :second_name, class: 'form-control', required: true %>
            </div>
          </h4>
          <div class="field">
            Імя<br>
            <%= f.text_field :name, class: 'form-control', required: true %>
          </div>
          <div class="field">
            По батькові<br>
            <%= f.text_field :surname, class: 'form-control', required: true %>
          </div>
          <p>
            <i class="fa fa-circle-o"></i>
            Категорія <%= f.text_field :category, class: 'form-control', required: true %>
            <i class="fa fa-circle-o"></i>
            Спеціалізація <%= f.text_field :specialization, class: 'form-control', required: true %>
            <i class="fa fa-circle-o"></i> Емайл <%= f.email_field :email, class: 'form-control', required: true %>
            <i class="fa fa-link"></i> <a href="#">BlackTie.co</a>
          <div class="field">
            <%= f.label :password %><br>
            <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
          </div>

          </p>
        </div>

        <div class="actions text-center">
          <%= f.submit 'Оновити', :class => 'btn btn-primary' %>
        </div>
      </div><!-- row -->
    </div>
    <br>
<% end %>

<div class="container">
  <% if @doctor.schedule.present? %>
      <%= render @doctor.schedule %>
      <%= link_to 'РЕДАГУВАТИ', edit_schedule_path(@doctor.schedule), class: 'btn btn-info btn-block' %>
  <% else %>
      <div class="btn btn-danger btn-block">
        <br>
        <h1> нема розкладу</h1>
      </div>
  <% end %>
</div>

app/views/doctors/index.html.erb
<div id="blue">
  <div class="container">
    <div class="row centered">
      <div class="col-lg-8 col-lg-offset-2">
        <h4>Список всіх лікарів</h4>
      </div>
    </div><!-- row -->
  </div>
</div>

<div class="container">
  <% @doctors.each do |doctor| %>
          <div class="col-sm-12  doctor-list-item">
            <div class="container-fluid well span6">
              <div class="row-fluid">
                <div class="col-md-2">
                  <%= image_tag(doctor.photo.url(:medium), class: 'img-circle') %>
                </div>

                <div class="col-md-3">
                  <h3><%= doctor.surname %></h3>
                  <h3><%= doctor.name %></h3>
                  <h3><%= doctor.second_name %></h3>
                </div>
                <div class="col-md-5">
                  <h4>Лікар <%= doctor.category %> категорії </h4>
                  <h4>Спеціалізація  <%= doctor.specialization %> </h4>
                  <h4>Email: <%= doctor.email %></h4>

                </div>
                <div class="col-md-2">
                  <%= link_to 'Записатися до лікаря', doctor_path(doctor), class: 'btn btn-info btn-block' %>


                </div>
              </div>
            </div>
          </div>
      <% end %>
</div>

app/views/doctors/login.html.erb
<div class="container">
  <div class="row">
    <!-- Article main content -->
    <article class="col-xs-12 maincontent">
      <header class="page-header">
      </header>
      <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <div class="panel panel-default">
          <div class="panel-body">
            <h3 class="thin text-center">Sign in to your account</h3>
            <p class="text-center text-muted"></p>
            <hr>
            <form action="/doc/login">
              <div class="top-margin">
                <label>Email <span class="text-danger">*</span></label>
                <input type="email" name="email" class="form-control">
              </div>
              <div class="top-margin">
                <label>Password <span class="text-danger">*</span></label>
                <input type="password" name="password" class="form-control">
              </div>
              <hr>
              <div class="row">
                <div class="thin text-center">
                  <input type="submit" class="btn btn-success">
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </article>
    <!-- /Article -->
  </div>
</div>  <!-- /container -->

app/views/doctors/show.html.erb
<div id="blue">
  <div class="container">
    <div class="row centered">
      <div class="col-lg-8 col-lg-offset-2">
        <h4>Доктор</h4>

      </div>
    </div><!-- row -->
  </div>
</div>
<div class="container">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 centered">
        <div class="tilt">
          <%= image_tag(@doctor.photo.url(:medium), class: 'img-circle') %>
          <% if current_doctor.present? %>
              <%= link_to 'Logout', doc_logout_path, class: 'btn btn-danger' %>

          <% end %>
        </div>
      </div><!-- col-lg-6 -->
      <div class="col-lg-6">
        <h4>Лікар</h4>
        <h4>
          <div class="field">
            Прізвище<br>
            <%= @doctor.second_name %>
          </div>
        </h4>
        <div class="field">
          Імя<br>
          <%= @doctor.name %>
        </div>
        <div class="field">
          По батькові<br>
          <%= @doctor.surname %>
        </div>
        <p>
          <i class="fa fa-circle-o"></i>
          Категорія <%= @doctor.category %>
          <br>
          <i class="fa fa-circle-o"></i>
          Спеціалізація <%= @doctor.specialization %>
          <br>
          <i class="fa fa-circle-o"></i> Емайл <%= @doctor.email %>
          <br>
          <i class="fa fa-link"></i> <a href="#">BlackTie.co</a>
        </p>
      </div>

    </div><!-- row -->
  </div>

  <div class="container">
    <table class="table table-condensed">
      <thead>

      </thead>
      <tbody>
      <tr>
        <% doctor = @doctor %>
        <% index = Date.today.at_beginning_of_week %>
        <th>Ім'я лікаря</th>
        <% today = Date.today %>
        <% (today.at_beginning_of_week..today.at_end_of_week).map.each do |day| %>
            <th><%= day.strftime("%A - %D") %></th>
        <% end %>
      </tr>
      <tr>
        <td><%= doctor.name %></td>
        <% Date::DAYNAMES.rotate(1).each do |weekday| %>
            <td>
              <% index = index + 1.day %>
              <div class="btn-success"> <%= p index-1.day %> </div>
              <br>
              <% if is_weekend?(doctor.current_schedule, weekday) %>
                  <p align="center" class="btn-danger"><br>Вихідний</p>
              <% else %>
                  <% if Time.now.to_i < index.to_time.to_i %>
                      <p align="center" class="btn-warning">Час роботи<br>
                        <%= doctor.current_schedule.send(weekday.downcase+'_start_time').strftime("%H - %M :") %>
                        <%= doctor.current_schedule.send(weekday.downcase+'_finish_time').strftime("%H - %M") %>
                      </p>
                      <br>
                      <% (doctor.current_schedule.send(weekday.downcase+'_start_time').to_i..doctor.current_schedule.send(weekday.downcase+'_finish_time').to_i).step(doctor.current_schedule.interval.minutes).to_a[0...-1].each do |interval| %>


                          <% iteration_day = index - 1.day %>
                          <% iteration_time = Time.at(interval).utc %>
                          <% record_time = Time.new(iteration_day.year, iteration_day.month, iteration_day.day, iteration_time.hour, iteration_time.min, '00:00') %>
                          <% if Record.where(time: record_time, doctor_id: doctor.id).present? %>
                              <% if current_doctor %>
                                  <%= iteration_time.strftime("%H - %M") %>
                                  <%= Record.where(time: record_time, doctor_id: doctor.id).first.user.name %>
                                  <%= Record.where(time: record_time, doctor_id: doctor.id).first.user.surname %>
                              <% else %>
                                  <% if current_user %>
                                      <span class="btn-danger"> <%= 'Ваш запис' %></span>
                                  <% else %>
                                      <span class="btn-success">  <%= 'Занято' %></span>
                                  <% end %>
                              <% end %>
                          <% elsif current_user %>
                              <% if record_time.to_i<Time.now.to_i %>
                                  <span class="alert-danger ">Час вийшов</span>
                              <% else %>
                                  <%= link_to(iteration_time.strftime("%H - %M"), records_path(user_id: current_user, doctor_id: doctor.id, time: record_time), method: :post, data: {confirm: 'Для запису до лікаря введіть його Призвище', verify: doctor.second_name, verify_text: doctor.second_name}) %>
                              <% end %>
                          <% else %>
                              <%= iteration_time.strftime("%H - %M") %>
                          <% end %>
                          <br>
                      <% end %>
                  <% else %>
                      <p align="center" class="btn-warning"> Даний день уже закінчився </p>
                  <% end %>
              <% end %>
            </td>
        <% end %>
      </tr>
      </tbody>
    </table>
  </div>
  <h3>Відгуки</h3>
  <div id="comments-container">
    <%= render @comments %>
  </div>
  <div id="add_comment">
    <% if current_user %>
        <%= render 'comments/form' %>
    <% end %>
  </div>
</div>

app/views/doctors/update.html.erb
<h1>Doctors#update</h1>
<p>Find me in app/views/doctors/update.html.erb</p>