config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'

  get 'comments/destroy'

  resources :comments, only: [:edit, :destroy]

  devise_for :companies
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  get 'search_suggestions' => 'doctors#search_suggestions', as: :search_suggestions

  resources :doctors, only: [:show, :index, :create, :update, :edit, :destroy] do
    get 'send_password', to: 'doctors#send_password', on: :collection
    resources :comments, only: [:create]
  end

  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/services'
  get 'welcome/works'

  get 'companies/index', to: 'companies#index'
  resources :companies, only: [:show, :index, :create, :update, :edit, :destroy] do
    resources :comments, only: [:create]
  end
  get 'company/doctors', to: 'companies#doctors'
  get 'company/schedule', to: 'companies#schedule'

  root 'welcome#index'

  get 'doc', to: 'doctors#login'
  match 'doc/login', to: 'doctors#create_session', via: [:put, :patch, :get]
  match 'doc/logout', to: 'doctors#logout', via: [:put, :patch, :get]

  resources :schedules, only: [:show, :new,  :create, :update, :edit, :destroy]
  resources :records, only: [:create, :destroy]

end

app/views/layouts/_header.html.erb
<!-- Fixed navbar -->
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">MEDICINE</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= current_page?(companies_index_path) ? 'active' : '' %>"><%= link_to('Список компаній', companies_index_path) %></li>
        <li class="<%= current_page?(doctors_path) ? 'active' : '' %>"><%= link_to 'Cписок лікарів', doctors_path  %></li>
        <% if current_company %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_company.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li> <%= link_to 'Profile', edit_company_registration_path %> </li>
                <li role="separator" class="divider"></li>
                <li> <%= link_to 'Doctors', company_doctors_path %> </li>
                <li role="separator" class="divider"></li>
                <li> <%= link_to 'Schedule', company_schedule_path %> </li>
                <li role="separator" class="divider"></li>
                <li> <%= link_to 'Выход', destroy_company_session_path, method: 'delete' %></li>
              </ul>
            </li>
        <% elsif current_user %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li> <%= link_to 'Кабинет', edit_user_registration_path %> </li>
                <li role="separator" class="divider"></li>                
                <li> <%= link_to 'Выход', destroy_user_session_path, method: 'delete' %></li>
              </ul>
            </li>
        <% else %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Компаниям<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li> <%= link_to 'Регистрация', new_company_registration_path , data: {no_turbolink: true}%> </li>
                <li role="separator" class="divider"></li>
                <li> <%= link_to 'Вход', new_company_session_path %></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Пользователям<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li> <%= link_to 'Регистрация', new_user_registration_path %> </li>
                <li role="separator" class="divider"></li>
                <li> <%= link_to 'Вход', new_user_session_path %></li>
              </ul>
            </li>
        <% end %>
      </ul>



    </div><!--/.nav-collapse -->
  </div>

</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Medicine</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="http://maps.googleapis.com/maps/api/js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <%= render 'layouts/messages' %>

<%= yield %>

</body>
</html>